---
title: Results of RCNN model to Detect Construction Type Opus Incertum for selected
  models.
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

This is a notebook of results for selected models to analyse which one will be selected as the best.
 


```{r}

graph_result <- function(cfg_name,construction_type) {
  library("ggplot2")
  library("ggthemes")
  
  image_prediction_folder <-
  paste0(
  '/home/student/data_5000_project/data/images/construction_types/processed/',construction_type,'/predictions/',
  cfg_name,
  "/unknown/"
  )
  results <-
  read.table(
  paste0(image_prediction_folder, "results_", cfg_name, ".csv"),
  header = TRUE,
  sep = ",",
  dec = "."
  )
  results_df <- data.frame(results)
  
  g1p <- ggplot(results_df, aes(min_score)) +
  geom_line(aes(y = gt_obj_pres_pos , colour = "Ground Truth: Present"),
  linetype = 2) +
  geom_line(aes(y = tp , colour = "Prediction: TP")) +
  geom_line(aes(y = fp , colour = "Prediction: FP")) +
  theme_igray() +
  ggtitle(paste0(construction_type," Present in Image. Model: ", cfg_name)) +
  xlab("Minimum Prediction Confidence Score Used") +
  ylab("Number of Occurences")
  
  g1n <- ggplot(results_df, aes(min_score)) +
  geom_line(aes(y = gt_obj_pres_neg , colour = "Ground Truth: Not Present"),
  linetype = 2) +
  geom_line(aes(y = tn , colour = "Prediction: TN")) +
  geom_line(aes(y = fn , colour = "Prediction: FN")) +
  theme_igray() +
  ggtitle(paste0(construction_type," Not Present in Image. Model: ", cfg_name)) +
  xlab("Minimum Prediction Confidence Score Used") +
  ylab("Number of Occurences")
  
  g2 <- ggplot(results_df, aes(min_score)) +
  geom_line(aes(y = tp_box , colour = "Prediction Boxes: True Positive (TP)")) +
  geom_line(aes(y = fp_box , colour = "Prediction Boxes: False Positive (FP)")) + theme_minimal() +
  theme_igray() +
  ggtitle(paste0("Prediction Regions, True vs. False Positives. Model: ", cfg_name)) +
  xlab("Minimum Prediction Confidence Score Used") +
  ylab("Number of Occurences")
  
  print(g1p)
  
  print(g1n)
  
  print(g2)
  
  results_df <- within(results_df, accuracy <- ((tp + tn) / (tp + tn + fp +
  fn)))
  results_df <- within(results_df, sn <- ((tp) / (tp + fn)))
  results_df <- within(results_df, sp <- ((tn) / (tn + fp)))
  results_df <- within(results_df, ppv <- ((tp) / (tp + fp)))
  results_df <- within(results_df, npv <- ((tn) / (tn + fn)))
  print(results_df)
  g3 <- ggplot(results_df, aes(min_score)) +
  geom_line(aes(y = accuracy , colour = "Accuracy"), linetype=2) +
  geom_line(aes(y = sn , colour = "Sensitivity/Recall/True Positive Rate")) +
  geom_line(aes(y = sp , colour = "Specificity")) +
  theme_igray() +
  ggtitle(paste0("Sensitivity and Specificity. Model: ", cfg_name)) +
  xlab("Minimum Prediction Confidence Score Used") +
  ylab("% Accuracy")
  
  print(g3)
  
  g4 <- ggplot(results_df, aes(min_score)) +
  geom_line(aes(y = accuracy , colour = "Accuracy"), linetype=2) +
  geom_line(aes(y = ppv , colour =  "Positive Predictive Value")) +
  geom_line(aes(y = npv , colour = "Negative Predictive Value")) +
  theme_igray() +
  ggtitle(paste0("Predictive Value. Model: ", cfg_name)) +
  xlab("Minimum Prediction Confidence Score Used") +
  ylab("% Accuracy")
  
  print(g4)
  
}
```

# Opus incertum
# Model cfg20200307T0901
## Epochs = 5

```{r}
cfg_name <- 'cfg20200307T0901'
construction_type <- 'opus_incertum'
graph_result(cfg_name,construction_type)

```

# Opus incertum
# Model cfg20200318T1120
## Epochs = 40
```{r}
cfg_name <- 'cfg20200318T1120'
construction_type <- 'opus_incertum'
graph_result(cfg_name,construction_type)
```


# Opus incertum
# Model cfg20200325T2048
## Epochs = 25
```{r}
cfg_name <- 'cfg20200325T2048'
construction_type <- 'opus_incertum'
graph_result(cfg_name,construction_type)
```

# Opus Latericium - Opus Testaceum
# Model cfg20200405T1031
## Epochs = 40
```{r}
cfg_name <- 'cfg20200405T1031'
construction_type <- 'opus_latericium_-_opus_testaceum'
graph_result(cfg_name,construction_type)

```

# Opus Vittatum Mixtum
# Model cfg20200405T1638
## Epochs = 40
```{r}
cfg_name <- 'cfg20200405T1638'
construction_type <- 'opus_vittatum_mixtum'
graph_result(cfg_name,construction_type)
```




